image:
  registry: repo.gcg.name/gcg-docker
  secret: docker-ro

quota:
  memory:
    limit: 64Mi
    request: 32Mi
  cpu:
    limit: 50m
    request: 25m

probe:
  liveness:
    enabled: true
    initialDelay: 10
    period: 10
  readiness:
    enabled: true
    initialDelay: 10
    period: 10

service:
  intPort: 8080
  monPort: 8080
  name: s-akula-ui

ingress:
  dns: akula.gcg.name
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
