stages:
  - validate
  - build
  - publish
  - deploy

validate:helm:
  stage: validate
  image: dtzar/helm-kubectl:3
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      exists:
        - "*/Chart.yaml"
  script:
    - helm version
    - helm lint ./chart/

build:helm:
  stage: build
  image: dtzar/helm-kubectl:3
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
    - if: $CI_COMMIT_TAG
  before_script:
    - export APP_VERSION=$(cat package.json | jq -r '.version')-${CI_COMMIT_SHORT_SHA}
    - |
      if [ $CI_COMMIT_TAG ]; then
      export CHART_VERSION=${CI_COMMIT_TAG:1} ;
      else
      export CHART_VERSION=${APP_VERSION} ;
      fi
  script:
    - echo $APP_VERSION
    - echo $CHART_VERSION
    - helm version
    - cd ./chart/
    - helm package . --app-version ${APP_VERSION} --version ${CHART_VERSION}
  artifacts:
    paths:
      - ./chart/*.tgz
    expire_in: 1 day

build:npm:
  stage: build
  image: node:21.2.0
  before_script:
    - unset CI
    - npm install --package-lock
  script:
    - npm run build
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - node_modules/
  artifacts:
    paths:
      - build/
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"'
      exists:
        - "package.json"

publish:docker:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      exists:
        - "Dockerfile"
  before_script:
    - export APP_VERSION=$(sed -n 's/.*"version":[ ]*"\([^"]*\).*/\1/p' package.json)-${CI_COMMIT_SHORT_SHA}
    - echo "{\"auths\":{\"$DOCKER_REPO\":{\"username\":\"$DOCKER_USER_RW\",\"password\":\"$DOCKER_PASSWORD_RW\"}}}" > /kaniko/.docker/config.json
  script:
    - echo $APP_VERSION
    - time /kaniko/executor
        --context $CI_PROJECT_DIR
        --dockerfile $CI_PROJECT_DIR/Dockerfile
        --destination $DOCKER_REPO/$CI_PROJECT_NAME:$APP_VERSION
        --cache=false
        --verbosity=debug
    - echo "Docker Image Name:" $DOCKER_REPO/$CI_PROJECT_NAME:$APP_VERSION

publish:helm:
  image: alpine:3
  stage: publish
  only:
    - test
  before_script:
    - apk add curl jq
    - export APP_VERSION=$(cat package.json | jq -r '.version')-${CI_COMMIT_SHORT_SHA}
    - |
      if [ $CI_COMMIT_TAG ]; then
      export CHART_VERSION=${CI_COMMIT_TAG:1} ;
      else
      export CHART_VERSION=${APP_VERSION} ;
      fi
  script:
    - curl -u ${HELM_USER_RW}:${HELM_PASSWORD_RW} -X PUT "${HELM_REPO}/${CI_PROJECT_NAME}-${CHART_VERSION}.tgz" -T ./chart/${CI_PROJECT_NAME}-${CHART_VERSION}.tgz

deploy:test:
  stage: deploy
  image: dtzar/helm-kubectl:3
  only:
    - test
  before_script:
    - export APP_VERSION=$(cat package.json | jq -r '.version')-${CI_COMMIT_SHORT_SHA}
    - |
      if [ $CI_COMMIT_TAG ]; then
      export CHART_VERSION=${CI_COMMIT_TAG:1} ;
      else
      export CHART_VERSION=${APP_VERSION} ;
      fi
    - curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - helm repo add ${HELM_REPO_ALIAS} --force-update --username "$HELM_USER_RO" --password "$HELM_PASSWORD_RO" "${HELM_REPO}"
    - helm repo update
  script:
    - helm version
    - time helm upgrade ${CI_PROJECT_NAME} ${HELM_REPO_ALIAS}/${CI_PROJECT_NAME}
      --install
      --wait
      --version ${CHART_VERSION}
      --namespace ${TEST_NS}
      --set ingress.dns=${TEST_DOMAIN}
    - helm list -n ${TEST_NS}

deploy:prod:
  stage: deploy
  image: dtzar/helm-kubectl:3
  only:
    - master
  before_script:
    - apk update
    - apk add sshpass openssh
    - export APP_VERSION=$(cat package.json | jq -r '.version')-${CI_COMMIT_SHORT_SHA}
    - |
      if [ $CI_COMMIT_TAG ]; then
      export CHART_VERSION=${CI_COMMIT_TAG:1} ;
      else
      export CHART_VERSION=${APP_VERSION} ;
      fi
    - curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm
    - chmod +x /usr/local/bin/helm
    - sshpass -p ${PROD_PASSWORD} ssh -o StrictHostKeyChecking=no -fNT -L 56443:127.0.0.1:6443 ${PROD_USER}@${PROD_HOST}

    - kubectl config set-cluster k8s --server="https://127.0.0.1:56443/" --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab --token="${PROD_KUBE_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab --namespace=${PROD_NS}
    - kubectl config use-context default

    - helm repo add ${HELM_REPO_ALIAS} --force-update --username "$HELM_USER_RO" --password "$HELM_PASSWORD_RO" "${HELM_REPO}"
    - helm repo update
  script:
    - helm version
    - time helm upgrade ${CI_PROJECT_NAME} ${HELM_REPO_ALIAS}/${CI_PROJECT_NAME}
      --install
      --wait
      --version ${CHART_VERSION}
      --namespace ${PROD_NS}
      --set ingress.dns=${PROD_DOMAIN}
      --set image.secret=${PROD_DOCKER_USER_RO}
    - helm list -n ${PROD_NS}
